version: '3.6'
services:
    graphql-polymorphism:
        container_name: graphql-docker
        build: .
        expose:
            - 80
        ports:
            - "80:80"
        logging:
            driver: json-file
        environment:
            - FLASK_ENV=dev